// Generated by ui-ux-pro-max: "global product launch map tech bold dark" --design-system
export const BG = "#0B0B10";
export const FG = "#F8FAFC";
export const ACCENT = "#3B82F6";
export const CARD = "#1E1E23";
export const MUTED_FG = "#94A3B8";
export const BORDER = "#1E293B";

export const FONT_DISPLAY = "'Exo', system-ui, sans-serif";
export const FONT_MONO = "'Roboto Mono', ui-monospace, monospace";
